project:
  type: website
  title: "Страница семинара Лаборатории Больших Случайных Систем"
  output-dir: docs


website:
  description: "Сайт лаборатории для публикации статей, семинаров и материалов."
  navbar:
    left:
      - text: ""
        href: index.qmd
      #- text: "Сотрудники"
      #  href: staff.qmd
      #- text: "История"
      #  href: history.qmd
      #- text: "Публикации"
      #  href: publications.qmd
      #- text: "Спецкурсы"
      #  href: courses.qmd
      

