<!--- # Лаборатория Больших Случайных Систем -->
## Семинар Лаборатории Больших Случайных Систем "Многокомпонентные системы и математическая физика" (рук. Замятин А.А., Калимулина Э.Ю., Манита А.Д., Меликян М.В.)
### Время и место проведения: ГЗ МГУ, среда	18:30-20:05, ауд.1613 

<!--- Обратите внимание, что в осеннем семестре 24/25 семинар также иногда проходит по понедельникам 18.30, ауд.1604 ГЗ МГУ. Для точнения информации следите за [анонсами докладов](#осенний-семестр-2024) на данной странице. -->

---

<!--- # Семинары лаборатории -->

## Переход по семестрам:
- [Весенний семестр 2025](#весенний-семестр-2025)
- [Осенний семестр 2024](#осенний-семестр-2024)
- [Весенний семестр 2024](#весенний-семестр-2024)
- [Осенний семестр 2023](#осенний-семестр-2023)
- [Весенний семестр 2023](#весенний-семестр-2023)
- [Осенний семестр 2022](#осенний-семестр-2022)

---

## Весенний семестр 2025


### 19 марта (среда) — семинар по курсовой работе  
**Докладчик:** Данила Зайцев (4 курс) 
**Тема:** Движение тяжелой частицы в случайной среде  
**Время:** 18:30  
**Аудитория:** 16-13  


### 12 марта (среда) — семинар по курсовой работе  
**Докладчик:** София Закрина (4 курс)  
**Тема:** Скорость роста кластера в случайной системе с бесконечным числом частиц  
**Время:** 18:30  
**Аудитория:** 16-13  



### 5 марта (среда) — семинар по курсовым работам  
**Докладчик:** Алина Мельникова (3 курс)  
**Тема:** Система обслуживания с ненадежным прибором  
**Время:** 18:30  
**Аудитория:** 16-13  



### 26 февраля (среда) — семинар по курсовым работам  
**Докладчики:**  
— Сергей Челышев (3 курс) *"Случайная динамика конечной системы частиц с взаимодействием"*  
— Алина Мельникова (3 курс) *"Система обслуживания с ненадежным прибором"*  
**Время:** 18:30  
**Аудитория:** 16-13  



### 19 февраля (среда) — первый семинар семестра  
**Докладчик:** Михаил Новак (6 курс)  
**Тема:** Асимптотика процесса накопления для бесконечной системы частиц с поглощением  
**Время:** 18:30  
**Аудитория:** 16-13  



---

## Осенний семестр 2024


### 11 декабря (среда) - последний семинар семестра  
**Докладчик:** Е. Белоножка (5 курс), Д. Зайцев (4 курс)  
**Тема:** Обсуждение курсовых работ  
**Время:** 18:30  
**Аудитория:** 16-13      
<details>
  <summary>Аннотация:</summary>
  Будем обсуждать курсовые работы
  Е. Белоножки (5 курс) "Исследование возвратности (невозвратности) марковских цепей с помощью метода электрических цепей" и Д. Зайцева (4 курс) "Бесконечные системы частиц с упругими столкновениями".
</details>


### 4 декабря (среда)
**Докладчик:** А.А. Замятин (МГУ)  
**Тема:** "Классификация счетных цепей Маркова с помощью функций Ляпунова (продолжение)"  
**Время:** 18:30  
**Аудитория:** 16-13      
<details>
  <summary>Аннотация:</summary>
Рассмотрим примеры применения этой техники.
</details>

### 27 ноября (среда)
**Докладчик:** А.А. Замятин (МГУ)  
**Тема:** "Классификация счетных цепей Маркова с помощью функций Ляпунова"  
**Время:** 18:30  
**Аудитория:** 16-13      
<details>
  <summary>Аннотация:</summary>
  Доклад носит учебный характер, специальных знаний не требуется. Будет рассказано, как получать достаточные условия эргодичности, возвратности, невозвратности счетных марковских цепей в терминах функций Ляпунова.
</details>


### 13 ноября (среда)
**Докладчик:** Илья Галаган (3 курс, МГУ)  
**Тема:** "Динамическая модель книги лимитных ордеров"  
**Время:** 18:30  
**Аудитория:** 16-13      
<details>
  <summary>Аннотация:</summary>
  Доклад по материалам статьи:  Rosu, Ioanid, A Dynamic Model of the Limit Order Book (June 6, 2008).   SSRN: <https://ssrn.com/abstract=710841>.  
  Работа посвящена изучению модели рынка, основанного на лимитных ордерах, где стратегически настроенные трейдеры с симметричной информацией по ликвидности
   динамично выбирают между лимитными и рыночными ордерами, балансируя цену исполнения и затраты на ожидание. Будет рассмотрено, как модель предсказывает несколько эмпирических эффектов. 
</details>


### 6 ноября (среда)
**Докладчик:** Андрей Андреевич Замятин   
**Тема:** "Невозвратность симметричного случайного блуждания в размерности 3 и выше"  
**Время:** 18:30  
**Аудитория:** 16-13      
<details>
  <summary>Аннотация:</summary>
  Доклад посвящен доказательству теоремы о невозвратности симметричного случайного блуждания в размерности 3 и больше методом электрических цепей.   
</details>

 
### 30 октября (среда)
**Докладчик:** Елена Белоножка (5 курс, МГУ)   
**Тема:** "Электрические сети и случайные блуждания (продолжение доклада)"  
**Время:** 18:30  
**Аудитория:** 16-13      
<details>
  <summary>Аннотация:</summary>
  Доклад посвящен доказательству теоремы о невозвратности симметричного случайного блуждания в размерности 3 и больше методом электрических цепей. 
  Доклад основан на материалах работы:  Nachmias, A. (2020). Random Walks and Electric Networks. In: Planar Maps, Random Walks and Circle Packing. Lecture Notes in Mathematics(), vol 2243. Springer, Cham.
  <https://doi.org/10.1007/978-3-030-27968-4_2> 
</details>

 
### 23 октября (среда)
**Докладчик:** Елена Белоножка (5 курс, МГУ)   
**Тема:** "Электрические сети и случайные блуждания"  
**Время:** 18:30  
**Аудитория:** 16-13      
<details>
  <summary>Аннотация:</summary>
  Доклад посвящен доказательству теоремы о невозвратности симметричного случайного блуждания в размерности 3 и больше методом электрических цепей. 
</details>


### 16 октября (среда)
**Докладчик:** Данила Зайцев (4 курс, МГУ)  
**Тема:** "Движение тяжелой частицы для систем бильярдного типа"  
**Время:** 18:30  
**Аудитория:** 16-13 
<details>
  <summary>Аннотация:</summary>
  Доклад по материалам статьи:  
*Richard Holley, The Motion of a Large Particle. Transactions of the American Mathematical Society, Vol. 144 (Oct., 1969), pp. 523-534*, <https://www.jstor.org/stable/1995295>. 
</details>     


### 09 октября (среда)
**Докладчик:** Всеволод Заостровский (студент 5 курса МГУ)  
**Тема:** "Модель лимитной книги заявок Обижаевой-Ванга"  
**Время:** 18:30  
**Аудитория:** 16-13     

  
### 02 октября (среда)
**Докладчик:** Эльмира Калимулина (с.н.с., МГУ)  
**Тема:** "Some Aspects of Research on Queuing Networks
with Dynamic Structure"  
**Время:** 18:30  
**Аудитория:** 16-13     
<details>
  <summary>Аннотация:</summary>
  This work examines specific models of queuing networks where the network structure evolves over time. The ergodicity of Jackson networks on random graphs is studied, along with the behaviour of these networks depending on the dynamics of their structure. Some well-known approaches are applied, and it is shown that similar results to classical ones can be obtained even under relaxed conditions.
</details>



<!--- ### 23 сентября (понедельник)
**Докладчик:** Илья Галаган (3 курс)  
**Тема:** "????"  
**Время:** 18:30  
**Аудитория:** 16-04   
**Аннотация:**  ...



### 16 сентября (<red> red color markdown text</red> понедельник)
**Докладчик:** Никита Соболев (3 курс)  
**Тема:** "????"  
**Время:** 18:30  
**Аудитория:** 16-04  
**Аннотация:**  ... -->


---

## Весенний семестр 2024

### 22 мая
**Докладчик:** М. Новак (5 курс)  
**Тема:** "О накоплении частиц на границе"  
**Время:** 18:30  
**Аудитория:** 16-04


### 15 мая
**Докладчик:** Калимулина Э.Ю. (с.н.с., ИППИ РАН)   
**Тема:** "Некоторые задачи из теории очередей"  (продолжение)   
**Аннотация:**  Будут рассмотрены сети Джексона и их модификации. Специальные знания не требуются, доклад доступен для студентов 2-6 курсов.  
**Время:** 18:30  
**Аудитория:** 16-04


### 24 апреля
**Докладчик:** Калимулина Э.Ю. (с.н.с., ИППИ РАН)  
**Тема:** "Некоторые задачи из теории очередей"  
**Аннотация:** Доклад посвящен задачам из теории сетей массового обслуживания. Будут рассмотрены классические постановки, их модификации и подходы к анализу. Специальные знания не требуются, доклад доступен для студентов 2-6 курсов.  
**Время:** 18:30  
**Аудитория:** 16-04

### 3 апреля
**Докладчики:** А. Замятин, И. Краснов  
**Тема:** "Цепи Маркова со счетным числом состояний и с дискретным временем"  
**Время:** 18:30  
**Аудитория:** 16-04  
**Аннотация:** Рассчитан на студентов 2-5 курсов.

### 27 марта
**Докладчик:** М.В. Меликян  
**Тема:** "Случайные блуждания на решетке"  
**Время:** 18:30  
**Аудитория:** 16-04  
**Аннотация:** Рассчитан на студентов 2-5 курсов.

### 20 марта
**Докладчик:** Владислав Каменский (со-основатель и исполнительный директор финансовой компании «Викинг»)  
**Тема:** "Профессиональная арбитражная торговля и технологии"  
**Аннотация:**
1. Практическое применение математики в HFT и арбитраже.  
2. Описание карьерных возможностей в высокооплачиваемой индустрии HFT.  
3. Интеллектуальные вызовы и задачи с применением статистики, анализа данных и машинного обучения.    
**Время:** 18:30  
**Аудитория:** 16-04

### 13 марта
**Докладчик:** Е.А. Жижина (ведущий научный сотрудник, ИППИ РАН)    
**Тема:** "Маркированные модели контактов" (продолжение доклада)  
**Время:** 18:30  
**Аудитория:** 16-04

### 6 марта
**Докладчик:** А.А. Замятин  
**Тема:** "Счетные цепи Маркова с непрерывным временем"  
**Аннотация:** Рассчитан на студентов 3-5 курсов.  
**Время:** 18:30  
**Аудитория:** 16-04

### 28 февраля
**Докладчик:** М.В. Меликян  
**Тема:** "Цепи Маркова с дискретным временем"  
**Аннотация:** Рассчитан на студентов 3-5 курсов.  
**Время:** 18:30  
**Аудитория:** 16-04

### 21 февраля
**Докладчик:** Е.А. Жижина (ведущий научный сотрудник, ИППИ РАН)    
**Тема:** "Модели контактов в непрерывном пространстве"  
**Аннотация:** Обзор результатов совместных работ с С.А. Пироговым и новые задачи.  
**Время:** 18:30  
**Аудитория:** 16-04

---

## Осенний семестр 2023

### 6 декабря
**Докладчик:** М.В. Новак (5 курс)  
**Тема:** "О некоторых классических результатах в теории случайных блужданий"  
**Время:** 18:30  
**Аудитория:** 16-04

### 22 ноября
**Докладчик:** М.В. Новак (5 курс)  
**Тема:** "О среднем числе поглощений для одной системы с бесконечным числом частиц"  
**Время:** 18:30  
**Аудитория:** 16-04

### 15 ноября
**Докладчики:** А.А. Лыков, М.В. Меликян  
**Тема:** "О тепловом эхо в одномерном закрепленном кристалле"  
**Время:** 18:30  
**Аудитория:** 16-04

### 1 ноября
**Докладчики:** А.А. Лыков, М.В. Меликян  
**Тема:** "О тепловом эхо в одномерном закрепленном кристалле"  
**Время:** 18:30  
**Аудитория:** 16-04

### 25 октября
**Докладчики:**  
1. Кирилл Назаров (5 курс) — обсуждение модели статьи "A fluid queue driven by a Markovian queue" (1999, Bruno Sericola, Bruno Tuffin).  
2. Василий Коваленко (6 курс) — доклад "Сходимость функций распределения для систем с большим числом частиц".  
**Время:** 18:30  
**Аудитория:** 16-04

### 18 октября
**Докладчики:**  
1. Александра Гончарова (6 курс). Тема будет объявлена на семинаре.  
2. Кирилл Назаров — обсуждение модели статьи "A fluid queue driven by a Markovian queue" (1999, Bruno Sericola, Bruno Tuffin).  
**Время:** 18:30  
**Аудитория:** 16-04

### 11 октября
**Докладчики:** Котляров Николай, Луканин Максим  
**Тема:** "Оценка скорости сходимости порога решающего стампа"  
**Время:** 18:30  
**Аудитория:** 16-04

### 4 октября
**Докладчик:** И.В. Краснов  
**Тема:** "Динамика книги ордеров на ликвидных рынках" _(продолжение доклада)_  
**Время:** 18:30  
**Аудитория:** 16-04

### 27 сентября
**Докладчик:** И.В. Краснов  
**Тема:** "Динамика книги ордеров на ликвидных рынках"  
**Время:** 18:30  
**Аудитория:** 16-04

### 20 сентября
**Докладчик:** Александр Лыков  
**Тема:** "Новый взгляд на управление портфелем активов"  
**Время:** 18:30  
**Аудитория:** 16-04

---

## Весенний семестр 2023

### 17 мая
**Докладчик:** Михаил Новак  
**Тема:** "О блуждании бесконечной системы частиц на Z_+"  
**Время:** 18:30  
**Аудитория:** 12-26а

### 10 мая
**Докладчик:** Александр Андреевич Лыков  
**Тема:** "Время возвращения кинетической температуры"  
**Время:** 18:30  
**Аудитория:** 12-26а

### 3 мая
**Семинара не будет.**

### 12 апреля
**Докладчик:** Денис Тумояков (6 курс)  
**Тема:** "Возмущенная модель голосования с множественным выбором"  
**Время:** 18:30  
**Аудитория:** 12-26а

### 5 апреля
Научная конференция **"ЛОМОНОСОВСКИЕ ЧТЕНИЯ–2023"**  


**Время:** 18:30  
**Место:** Главное здание, сектор «А», ауд. 14-14

#### Программа:
1. **Асимптотика вероятностей поглощения для случайных блужданий в областях с границами**  
   _Докладчики:_ ст. науч. сотр. Замятин А.А., асп. Краснов И.В.  
2. **Управление в одной модели социальной динамики со случайным шумом**  
   _Докладчики:_ доцент Манита А.Д., асп. Болычева А.  
3. **Новые результаты для бесконечных вероятностных моделей динамики мнений**  
   _Докладчики:_ доцент Манита А.Д., асп. Игнатовская В.А.

### 29 марта
**Докладчик:** М.В. Меликян  
**Тема:** "Введение в дифференциальные уравнения с запаздыванием"  
**Время:** 18:30  
**Аудитория:** 12-26а

### 15 марта
**Докладчики:** И. Краснов и А. Замятин  
**Тема:** "Вероятности поглощений для случайных блужданий в областях с границами" _(продолжение доклада)_  
**Время:** 18:30  
**Аудитория:** 12-26а

### 1 марта
**Докладчики:** И. Краснов и А. Замятин  
**Тема:** "Вероятности поглощений для случайных блужданий в областях с границами"  
**Время:** 18:30  
**Аудитория:** 12-26а

### 22 февраля
**Докладчик:** Александр Лыков  
**Тема:** "Задачи устойчивости цепочки гармонических осцилляторов"  
**Время:** 18:30  
**Аудитория:** 12-26а

### 15 февраля
**Докладчик:** Иван Краснов  
**Тема:** "Вероятности достижений для блужданий с границами"  
**Время:** 18:30  
**Аудитория:** 12-26а

---

## Осенний семестр 2022

### 14 декабря
**Докладчик:** Валерия Игнатовская  
**Тема:** "Вероятностный подход к исследованию поведения одной бесконечной системы частиц"  
**Время:** 14:15  
**Аудитория:** 12-26а

### 7 декабря
**Докладчики:** Г.А. Зверкина и Э.Ю. Калимулина  
**Тема:** "Об одном обобщении неравенства Лордена"  
**Время:** 14:15  
**Аудитория:** 12-26а

### 23 ноября
**Докладчик:** В.В. Козлов  
**Тема:** "Цепи Маркова в рекордной модели" _(продолжение доклада)_  
**Время:** 14:15  
**Аудитория:** 12-26а

### 16 ноября
**Докладчик:** В.В. Козлов  
**Тема:** "Цепи Маркова в рекордной модели"  
**Время:** 14:15  
**Аудитория:** 12-26а

### 9 ноября
**Докладчик:** Николай Котляров  
**Тема:** Сообщение  
**Время:** 14:15  
**Аудитория:** 12-26а

### 2 ноября
**Тема:** Связь случайных блужданий с электрическими сетями  
**Время:** 14:15  
**Аудитория:** 12-26а

### 26 октября
**Программа:**  
1. Связь случайных блужданий и электрических сетей  
2. Краткие сообщения М. Новака и Н. Котлярова о задачах прошлого года  
**Время:** 14:15  
**Аудитория:** 12-26а

### 19 октября
**Тема:** Семинар в Zoom (исключение)  
**Докладчик:** М. Меликян  
**Тема:** Введение в дискретные цепи Маркова  
**Время:** 14:10

### 12 октября
**Докладчик:** Василий Коваленко  
**Время:** 14:15  
**Аудитория:** 12-26а

### 28 сентября
**Докладчик:** Маргарита Меликян  
**Тема:** "Динамические системы и Марковские цепи с нуля"  
**Время:** 15:00  
**Формат:** Онлайн (Zoom)


